### ISSUE TITLE
Failing getOptimalPosition tests on master

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-utils#108]
https://travis-ci.org/ckeditor/ckeditor5/builds/181701427

A follow-up of https://github.com/ckeditor/ckeditor5-ui-default/issues/137.

**Comment by Reinmar** [comment]
Those tests still fail for me in this case:

```
gulp test --files=core,enter,list,typing,undo,utils
```

Failed ones:

```
✖ 14 tests failed

FAILED TESTS:
  getOptimalPosition
    for single position
      ✖ should return coordinates
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 80, top: 491, name: 'left' } to deeply equal { top: 100, left: 80, name: 'left' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:94:5)

    for multiple positions
      ✖ should return coordinates
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 80, top: 491, name: 'left' } to deeply equal { top: 100, left: 80, name: 'left' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:145:5)

      ✖ should return coordinates (position preference order)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 110, top: 491, name: 'right' } to deeply equal { top: 100, left: 110, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:156:5)

    with a limiter
      ✖ should return coordinates (#1)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: -20, top: 491, name: 'left' } to deeply equal { top: 100, left: -20, name: 'left' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:171:5)

      ✖ should return coordinates (#2)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: -20, top: 491, name: 'left' } to deeply equal { top: 100, left: -20, name: 'left' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:182:5)

    with fitInViewport on
      ✖ should return coordinates (#1)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 10, top: 491, name: 'right' } to deeply equal { top: 100, left: 10, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:197:5)

      ✖ should return coordinates (#2)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 10, top: 491, name: 'right' } to deeply equal { top: 100, left: 10, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:209:5)

      ✖ should return coordinates (#3)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 0, top: 501, name: 'bottom' } to deeply equal { top: 110, left: 0, name: 'bottom' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:221:5)

    with limiter and fitInViewport on
      ✖ should return coordinates (#1)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 10, top: 491, name: 'right' } to deeply equal { top: 100, left: 10, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:237:5)

      ✖ should return coordinates (#2)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 10, top: 491, name: 'right' } to deeply equal { top: 100, left: 10, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:249:5)

      ✖ should return coordinates (#3)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 0, top: 501, name: 'bottom' } to deeply equal { top: 110, left: 0, name: 'bottom' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:261:5)

      ✖ should return coordinates (#4)
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 10, top: 491, name: 'right' } to deeply equal { top: 100, left: 10, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:273:5)

      ✖ should return the very first coordinates if no fitting position with a positive intersection has been found
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { Object (left, top, ...) } to deeply equal { Object (left, top, ...) }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:285:5)

      ✖ should return the very first coordinates if limiter does not fit into the viewport
        Chrome 55.0.2883 (Mac OS X 10.12.1)
      AssertionError: expected { left: 10, top: 491, name: 'right' } to deeply equal { top: 100, left: 10, name: 'right' }
          at Assertion.assertEqual (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:774:19)
          at Assertion.ctx.(anonymous function) [as equal] (/www/ckeditor5/ckeditor5/node_modules/chai/chai.js:4192:25)
          at assertPosition (tests/utils/dom/position.js:326:28)
          at Context.it (tests/utils/dom/position.js:310:5)

```

**Comment by oleq** [comment]
This is a bad news. It means we (I) got to write a better env for mocking things.

**Comment by Reinmar** [comment]
It seems so. Sorry :D
