### ISSUE TITLE
CKEditorError should use JSON.stringify carefully

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#164]
I've been looking at a strange error:

```
    ✖ "before each" hook for "should be loaded"
      Chrome 59.0.3071 (Mac OS X 10.12.4)
    TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)
        at CKEditorError (webpack:///packages/ckeditor5-utils/src/ckeditorerror.js:35:0 <- packages/ckeditor5-heading/tests/heading.js:108:26)
        at ParagraphCommand.decorate (webpack:///packages/ckeditor5-utils/src/observablemixin.js:319:0 <- packages/ckeditor5-heading/tests/heading.js:6711:10)
```

And the problem turned out to be that `CKEditorError` tries to do `JSON.stringify()` on the data object (the details of the error).

This fails because for the particular error which was thrown we log an instance of an object which has circ refs. If it was logged correctly I would realise what's wrong much faster, but this weird issue made me tracking a different bug.

**Comment by scofalik** [comment]
Isn't it a known issue that we "struggle" with all the time?

Honestly, to be really safe, we should take care that each class should be inspected to check whether it doesn't have a circular reference, and if so, define its own `JSON.stringify`. We don't do it regularly because we forget.

From time to time problem like this appears and we (or at least I :P) look where is the circular reference.

Anyway, AFAICS, this is a problem that I encountered a few times already and I thought that we all are aware of it.

**Comment by Reinmar** [comment]
I wasn't aware of it so far. 

And the solution may be simpler – we iterate over the passed data's properties and write simple stringifcation for them because we need to handle the first level properties, but not further. If an object is encountered in one of those properties, it can be stringified to some `[object ClassName]` notation or something.
